version: "3"

services:
  tile38:
    image: tile38/tile38:1.23.0
    command: tile38-server -vv -p 9851
    ports:
      - 9851:9851
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi-tile38 
    restart: unless-stopped
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8001
    volumes:
        - ./src/:/usr/src/app
    ports:
        - 8001:8001
    env_file:
      - .env
