[tool.poetry]
name = "fastapi-tile38"
version = "0.1.0"
description = "Use Tile38 via FastAPI"
authors = ["Benjamin Ramser <legionaerr@googlemail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.63.0"
pyle38 = "^0.1.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
pre-commit = "^2.12.0"
mypy = "^0.812"
black = "^20.8b1"
gitlint = "^0.15.0"
poethepoet = "^0.10.0"
isort = "^5.8.0"
pytest-cov = "^2.11.1"
flake8 = "^3.9.0"
uvicorn = "^0.13.4"

[tool.poe.tasks]
test       = "poetry run pytest -vv -s tests/"
test-cov   = "poetry run pytest -vv -s --cov=fastapi-tile38 tests/"
mypy       = "poetry run mypy --config-file pyproject.toml"
lint       = "flake8 ."
up         = "docker-compose up"
down       = "docker-compose down"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
